version: '3.1'

services:
  db:
    image: postgres
    restart: always
    env_file:
      - .env
    # volumes:
    #   - postgres-data:/var/lib/postgresql/data
    ports:  # debug
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}'"]
      interval: 10s
      timeout: 3s
      retries: 3
  scraper:
    build: scraper
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
  app:
    build: app
    depends_on:
      db:
        condition: service_healthy
      scraper:
        condition: service_completed_successfully
    ports:
      - "8080:8050"
    env_file:
      - .env